Health-Education-England/tis-trainee-details

build.gradle
src/main/java/uk/nhs/hee/trainee/details/TisTraineeDetailsApplication.java
src/main/java/uk/nhs/hee/trainee/details/api/ContactDetailsResource.java
src/main/java/uk/nhs/hee/trainee/details/dto/ContactDetailsDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/CurriculumDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/ProgrammeMembershipDto.java
src/test/java/uk/nhs/hee/trainee/details/repository/ContactDetailsRepositoryTest.java

fix: SonarCloud reported issues

---

.github/workflows/deploy.yml
Dockerfile
src/main/resources/application.properties

Create a build pipeline to create a docker image, push to Amazon ECR and trigger deploy.
TISNEW-3848

Create build pipeline

---

.github/workflows/deploy.yml

chore: Fix write image uri step in deploy pipeline

---

.github/workflows/deploy.yml

chore: Change uri location in deploy pipeline

---

.aws/task-definition.json
.github/workflows/deploy.yml

chore: Deploy to correct AWS cluster

---

.github/workflows/deploy.yml

chore: Fix task-def image value

---

.github/workflows/ci-cd-workflow.yml

chore: Fix pipeline file indentation

---

src/main/java/uk/nhs/hee/trainee/details/dto/CurriculumDto.java
src/main/java/uk/nhs/hee/trainee/details/model/Curriculum.java

add curriculumStartDate to filter most recent curriculum
TISNEW-3946

feat: add curriculumStartDate

---

src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDto.java
src/main/java/uk/nhs/hee/trainee/details/model/PersonalDetails.java

- prevRevalBody
- currRevalDate
- prevRevalDate
TISNEW-4283

feat: add Revalidation pre-populate fields for FormR-B

---

src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java
src/main/java/uk/nhs/hee/trainee/details/model/Placement.java

feat: add siteLocation field in Placement for Form R Part B

---

.actionspanel/buttons.yml
.github/workflows/ci-cd-workflow.yml
.github/workflows/purge-artifacts.yml

Add repository_dispatch workflow triggers to allow workflows to be
triggered via API.
Create buttons.yml with ActionsPanel button definition for triggering
the workflows.
NO-TICKET

chore: Add ActionsPanel buttons and triggers

---

.actionspanel/buttons.yml
.github/workflows/ci-cd-workflow.yml
.github/workflows/purge-artifacts.yml

Also update the pre-requisites for the dockerize job to no longer need
quality checks to pass (only build and test success/failure).
NO-TICKET

chore: Enabled manual workflow triggers

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/ContactDetailsResource.java
src/main/java/uk/nhs/hee/trainee/details/mapper/PersonalDetailsMapper.java
src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java
src/main/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImpl.java
src/main/java/uk/nhs/hee/trainee/details/service/impl/TraineeProfileServiceImpl.java
src/test/java/uk/nhs/hee/trainee/details/api/ContactDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/repository/TraineeProfileRepositoryTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImplTest.java

feat: Add patch endpoint to update contact details

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/dto/validation/Create.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/dto/TraineeProfileDtoTest.java

An endpoint is required to create an initial trainee profile. This
should not create multiple profiles for the same trainee TIS ID.
TISNEW-3833

feat: Add endpoint to create a trainee profile

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/GdcDetailsResource.java
src/main/java/uk/nhs/hee/trainee/details/api/GmcDetailsResource.java
src/main/java/uk/nhs/hee/trainee/details/api/PersonOwnerResource.java
src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java
src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java
src/main/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImpl.java
src/test/java/uk/nhs/hee/trainee/details/api/GdcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/GmcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/PersonOwnerResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImplTest.java

The GMC details, GDC details and Person Owner should be synchronized
from their own endpoints.
TISNEW-5238

feat: Add endpoints to sync GDC, GMC and Owner

---

.github/workflows/ci-cd-workflow.yml

fix: Explicitly push all docker tags

---

src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

Feat: add ability to delete programme memberships from person

---

src/main/java/uk/nhs/hee/trainee/details/config/MongoConfiguration.java
src/test/java/uk/nhs/hee/trainee/details/config/MongoConfigurationTest.java

Performance profiling here: https://hee-tis.atlassian.net/browse/TIS21-1274
TIS21-1238

feat: add DB index for TraineeProfile.traineeTisId

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java
src/main/java/uk/nhs/hee/trainee/details/mapper/PlacementMapper.java
src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java

Feat: delete placements

---

src/main/java/uk/nhs/hee/trainee/details/dto/CurriculumDto.java
src/main/java/uk/nhs/hee/trainee/details/model/Curriculum.java

feat: add curriculum end date

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/test/java/uk/nhs/hee/trainee/details/api/ContactDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/GdcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/GmcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/PersonOwnerResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/QualificationResourceTest.java

refactor: Resolve several code smells

---

src/test/java/uk/nhs/hee/trainee/details/repository/TraineeProfileRepositoryTest.java

refactor: Remove `public` mod from JUnit 5 tests

---

src/test/java/uk/nhs/hee/trainee/details/model/ProgrammeMembershipTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

test: improve test coverage

---

.github/workflows/ci-cd-workflow.yml
.github/workflows/pr-analysis.yml

chore: Rename master to main

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/QualificationResource.java
src/main/java/uk/nhs/hee/trainee/details/service/QualificationService.java
src/test/java/uk/nhs/hee/trainee/details/api/QualificationResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/QualificationServiceTest.java

Add an endpoint to delete qualifications by ID from a given trainee ID.
TIS21-2549

feat: add delete endpoint for qualifications

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

Create an endpoint to delete a trainee profile for a given TIS ID.
TIS21-2549

feat: add trainee profile delete endpoint

---

src/main/java/uk/nhs/hee/trainee/details/config/MongoConfiguration.java
src/test/java/uk/nhs/hee/trainee/details/config/MongoConfigurationTest.java

The existing index on TraineeTisId is not unique. This makes it unique.
This might be straying a bit into Mongock territory, so very happy to
refactor to use that if desired (it was actually how I implemented it at
first, but this way seems more concise).
Note that if Mongock is used, the MongoConfiguration should have
the ensureIndex() removed for traineeTisId, since this can throw an
exception if the existing index on that field has a different unique
value or has a different name, before Mongock can rework things.
TIS21-2923: Duplicate profile for trainee

feat: add unique index on TraineeTisId

---

.aws/task-definition-pre-prod.json
.aws/task-definition-prod.json
build.gradle
src/main/java/uk/nhs/hee/trainee/details/event/ProfileCreateEvent.java
src/main/java/uk/nhs/hee/trainee/details/service/EventPublishService.java
src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/trainee/details/service/EventPublishServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java

When a trainee profile is created, publish an event to an SQS queue.
TIS21-3001
TIS21-3104

feat: publish event on profile creation

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/TisTraineeDetailsApplication.java
src/main/java/uk/nhs/hee/trainee/details/migration/AddTraineeProfileVersioning.java
src/main/java/uk/nhs/hee/trainee/details/model/TraineeProfile.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/trainee/details/migration/AddTraineeProfileVersioningTest.java
src/test/java/uk/nhs/hee/trainee/details/repository/TraineeProfileRepositoryTest.java
src/test/resources/application.yml

This will support optimistic locking.
TIS21-3114: Ensure trainee profiles are always fully populated

feat: add TraineeProfile versioning

---

src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java

Given the need for a placement lookup I'm assuming we want a service method like this one, feel free to close the PR if you've already got an alternative in place.

feat: service method to get trainee placement

---

.aws/task-definition-pre-prod.json
.aws/task-definition-prod.json
build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/DspCredentialResource.java
src/main/java/uk/nhs/hee/trainee/details/config/DspConfigurationProperties.java
src/main/java/uk/nhs/hee/trainee/details/model/dsp/IssueTokenResponse.java
src/main/java/uk/nhs/hee/trainee/details/model/dsp/ParResponse.java
src/main/java/uk/nhs/hee/trainee/details/service/JwtService.java
src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/trainee/details/api/DspCredentialResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/JwtServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

Note: squash commit of https://github.com/Health-Education-England/tis-trainee-details/pull/263
Even as an alpha, for simplicity we can merge this into the main codebase since the endpoints will not be exposed by the API Gateway.
TIS21-3685

feat: issue DSP credential (alpha)

---

.aws/task-definition-pre-prod.json
.aws/task-definition-prod.json

chore: fix DSP secret names

---

.github/workflows/ci-cd.yml

chore: fix referenced workflow name

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDto.java
src/main/java/uk/nhs/hee/trainee/details/mapper/PersonalDetailsMapper.java
src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java
src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/ContactDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/GdcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/GmcDetailsResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/PersonOwnerResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/PersonalInfoResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java

The personal details data needs to be verifiable by other services, namely the credentials service. To achieve this the data should be signed in the same way as placements and programme memberships already are.
TIS21-4177
TIS21-4180

feat: sign personal details DTO

---

src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java

In javadoc and function name.
NO-TICKET

fix: bad copy-pasta

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/dto/ConditionsOfJoiningDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/enumeration/GoldGuideVersion.java
src/main/java/uk/nhs/hee/trainee/details/model/ConditionsOfJoining.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

Add a Conditions of Joining child DTO to the ProgrammeMembershipDTO allowing the recording of `signedAt` and `version` fields. Default the `version` to `GG9` if the CoJ is not signed, as a result signed data will appear as
```json
{
"conditionsOfJoining": {
"signedAt": "2023-01-01T00:00:00Z",
"version": "GG9"
}
}
```
With unsigned CoJ returned as
```json
{
"conditionsOfJoining": {
"signedAt": null,
"version": "GG9"
}
}
```
TIS21-4372

feat: add Conditions of Joining to PM DTO

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

fix: get existing CoJ from db not cache

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

fix: migrate PM CoJs signed during switch-over

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

Assumes a trainee will have an email, GMC and postcode.
(Not to be pushed further than preprod for now)
TIS21-4740

feat: trainee verification endpoint

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java
src/main/java/uk/nhs/hee/trainee/details/model/Placement.java
src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java

fix: add siteKnownAs field in TraineeProfile

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

Due to postcode data quality.
TIS21-4740

fix: trainee verification using DOB not postcode

---

.aws/task-definition-template.json
build.gradle
src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsEvent.java
src/main/java/uk/nhs/hee/trainee/details/event/BasicDetailsListener.java
src/main/java/uk/nhs/hee/trainee/details/event/ContactDetailsListener.java
src/main/java/uk/nhs/hee/trainee/details/event/GdcDetailsListener.java
src/main/java/uk/nhs/hee/trainee/details/event/GmcDetailsListener.java
src/main/java/uk/nhs/hee/trainee/details/event/PersonOwnerListener.java
src/main/java/uk/nhs/hee/trainee/details/event/PersonalInfoListener.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/trainee/details/event/BasicDetailsListenerTest.java
src/test/java/uk/nhs/hee/trainee/details/event/ContactDetailsListenerTest.java
src/test/java/uk/nhs/hee/trainee/details/event/GdcDetailsListenerTest.java
src/test/java/uk/nhs/hee/trainee/details/event/GmcDetailsListenerTest.java
src/test/java/uk/nhs/hee/trainee/details/event/PersonOwnerListenerTest.java
src/test/java/uk/nhs/hee/trainee/details/event/PersonalInfoListenerTest.java

Create SQS listeners for the following events:
- Basic detail updates
- Contact details updates
- GDC details updates
- GMC details updates
- Personal info updates
- Person Owner updates
TIS21-4076
TIS21-4086

feat: add event handlers for PersonDetails changes

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/config/SchedulePublishConfirmConfig.java
src/main/java/uk/nhs/hee/trainee/details/service/RabbitPublishService.java
src/main/resources/application.yml
src/test/java/uk/nhs/hee/trainee/details/config/SchedulePublishConfirmConfigTest.java
src/test/java/uk/nhs/hee/trainee/details/service/RabbitPublishServiceTest.java

feat: rabbit errors reported to sentry

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java
src/main/java/uk/nhs/hee/trainee/details/model/Placement.java
src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java

Best to merge https://github.com/Health-Education-England/tis-trainee-details/pull/375 first since it keeps the versioning sequential.
TIS21-4982

feat: placement postAllowsSubspecialties

---

build.gradle
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

This is needed if the trainee has not registered on TSS, when we will use their profile email instead of the cognito one.
TIS21-5208

feat: api endpoint to get trainee email

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/service/RabbitPublishService.java
src/test/java/uk/nhs/hee/trainee/details/service/RabbitPublishServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

Context: https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1707897608586209
TIS21-5725

feat: remove deprecated programme membership id handling

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
src/main/java/uk/nhs/hee/trainee/details/dto/UserAccountDetails.java
src/main/java/uk/nhs/hee/trainee/details/dto/UserDetails.java
src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java
src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java

feat: add GMC number in trainee account details endpoint

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

TIS21-5895
TIS21-5896
TIS21-5902

fix: pilot 2024 rule amendments

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

fix: add Health Education England South West into Pilot 2024

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

Exclude all General Practice, broaden date range.
TIS21-5943

fix: Y&H pilot 2024 rule change

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/SpecialtyDto.java
src/main/java/uk/nhs/hee/trainee/details/mapper/PlacementMapper.java
src/main/java/uk/nhs/hee/trainee/details/model/Placement.java
src/main/java/uk/nhs/hee/trainee/details/model/Specialty.java
src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java

To be followed by sync service PR to populate this new field.
TIS21-5742
TIS21-5743

feat: placement other specialties

---

src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java

Possibly this could be got from xray, but I don't know how :)
NO-TICKET

fix: log placement details

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/NtnGenerator.java
src/test/java/uk/nhs/hee/trainee/details/service/NtnGeneratorTest.java

Ignore any duplicated specialty codes when generating the NTN.
TIS21-6175

fix(ntn): do not include duplicate specialties

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/dto/ProgrammeMembershipDto.java
src/main/java/uk/nhs/hee/trainee/details/model/ProgrammeMembership.java
src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

feat: pm designated body

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/dto/HeeUserDto.java
src/main/java/uk/nhs/hee/trainee/details/dto/ProgrammeMembershipDto.java
src/main/java/uk/nhs/hee/trainee/details/model/HeeUser.java
src/main/java/uk/nhs/hee/trainee/details/model/ProgrammeMembership.java
src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

Relates to https://github.com/Health-Education-England/tis-trainee-sync/pull/474
TIS21-5826

feat: PM responsible officer

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java
src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java

fix: re-sign PM after training number set

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

As per conversation: https://hee-nhs-tis.slack.com/archives/C03G3UK3U82/p1728910424446039
TIS21-6562

fix: rollout placements without PM needing to be in pilot

---

.aws/task-definition-template.json
README.md
build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java
src/main/java/uk/nhs/hee/trainee/details/model/HrefType.java
src/main/java/uk/nhs/hee/trainee/details/model/LocalOfficeContactType.java
src/main/java/uk/nhs/hee/trainee/details/model/ProgrammeMembership.java
src/main/java/uk/nhs/hee/trainee/details/service/PdfGeneratingService.java
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/main/resources/application.yml
src/main/resources/templates/programme-confirmation/v1.0.0.html
src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/PdfGeneratingServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

TIS21-6483
TIS21-6514
TIS21-6515

feat: programme confirmation PDF

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/config/SqsConfigurationIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/config/SqsConfiguration.java
src/test/java/uk/nhs/hee/trainee/details/config/SqsConfigurationTest.java

fix: remove java type attribute from messages

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java
src/main/java/uk/nhs/hee/trainee/details/service/CctService.java
src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java

feat: update CCT (PUT endpoint)

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/mapper/CctMapper.java
src/main/java/uk/nhs/hee/trainee/details/service/CctService.java
src/test/java/uk/nhs/hee/trainee/details/mapper/CctMapperTest.java
src/test/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapperTest.java
src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java

feat: insert CCT date into responses

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java
src/main/java/uk/nhs/hee/trainee/details/service/CctService.java
src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java

fix: remove cct calculate endpoint

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java
src/main/java/uk/nhs/hee/trainee/details/mapper/CctMapper.java
src/main/java/uk/nhs/hee/trainee/details/service/CctService.java
src/test/java/uk/nhs/hee/trainee/details/mapper/CctMapperTest.java
src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java

feat: actual CCT calc

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/dto/CctCalculationDetailDto.java
src/main/java/uk/nhs/hee/trainee/details/model/CctCalculation.java
src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java

feat: add designatedBodyCode in CCT ProgrammeMembership

---

build.gradle.kts
src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java
src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java
src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java

fix: North East part of rollout now

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java
src/main/java/uk/nhs/hee/trainee/details/service/CctService.java
src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java
src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java

feat: delete CCT endpoint

---

build.gradle.kts
src/integrationTest/java/uk/nhs/hee/trainee/details/api/FeatureResourceIntegrationTest.java
src/main/java/uk/nhs/hee/trainee/details/dto/FeaturesDto.java
src/main/java/uk/nhs/hee/trainee/details/service/FeatureService.java
src/test/java/uk/nhs/hee/trainee/details/service/FeatureServiceTest.java

feat: include enabled programmes in FeaturesDTO
