.github/workflows/analyze-with-sonarqube.yml, build.gradle
Run Gradle's check task during the pipeline so that sonar can upload the
checkstyle reports.
TISNEW-3874
=> chore: Set up checkstyle sonar reporting

.github/workflows/deploy.yml
An ID is referenced in the docker build/push step to get the ECR
registry, but the ID was not declared on the correct step.
TISNEW-3848
=> chore: Add id to ECR login step of pipeline

.github/workflows/deploy.yml
As the repo was not checked out the Dockerfile was not accessible.
TISNEW-3848
=> chore: Add checkout step to dockerize job

.aws/task-definition.json, .github/workflows/deploy.yml
Create task-definition.json with default values for deploying an ECR
image, the image URI will be overwritten by a pipeline action.
Update deploy.yml to store the image-uri from the dockerize job and add
a deploy step to deploy the image in ECR to ECS.
TISNEW-3848
=> chore: Update pipeline to deploy ECR image

.github/workflows/deploy.yml
Currently a build artifact is used to pass through a plain text image
uri, get the registry name from logging in to ECR instead.
TISNEW-3848
=> chore: Get registry name from ECR login

.aws/task-definition.json
The service needs several env vars to be passed to connect to the
document db instance, the values for these are stored in AWS. Use the
secrets section to declared the environmental variables to be used.
TISNEW-3848
=> chore: Update task-definition to connect to DB

build.gradle
By addding this dependency, it automatically exposes two endpoints `/health` and `/info`. 
For `/info`, because there isn't any info configured for this project, it will just return a empty array.
Atm, we just need the `/health` endpoint, if we need to expose others, they can be configured later.
The whole api is `http://localhost:8023/actuator/health`.
=> chore: add spring-boot-starter-actuator

.github/workflows/ci-cd-workflow.yml
The analyze step runs `./gradlew check` when it does not need to, the
reports are provided from the check and test jobs.
TISNEW-3848
=> chore: Remove duplicate checks from build workflow

src/main/resources/application.properties
AWS ALB is unable to rewrite paths, so to avoid a separate nginx
instance the service must have its own context path.
TISNEW-3848
=> refactor: Set context path

build.gradle
The Spring Boot plugin can manage the version of Lombok, remove the
specific versions from the dependency declaration to allow that to
happen.
NO-TICKET
=> chore: Let Spring Boot determine Lombok version

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/main/java/uk/nhs/hee/trainee/details/service/impl/TraineeProfileServiceImpl.java, src/main/resources/application.properties, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
Currently the trainee's TIS ID is provided as part of the request URL,
as this needs to be locked down to only allow the logged in user to see
their own details the ID should be taken from the authorization token
instead.
TISNEW-3833
=> feat: Get trainee TIS ID from the token

build.gradle, src/main/java/uk/nhs/hee/trainee/details/mapper/PersonalDetailsMapper.java, src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java, src/main/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImpl.java, src/test/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImplTest.java
The update mapper for PersonalDetails attempts to update the existing
PersonalDetails for the TraineeProfile. In the case of a skeleton
profile being created this will be null and the update will throw a
NullPointerException.
Update the mappers in such a way that it will automatically create and
set the PersonalDetails field in the TraineeProfile as part of the
update if it is null.
TISNEW-3833
=> fix: Updating a trainee skeleton causes a NPE

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java, src/main/java/uk/nhs/hee/trainee/details/model/PersonalDetails.java, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/main/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImpl.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/impl/PersonalDetailsServiceImplTest.java
The public health number needs to be synced from the person table. Due
to the requirement of creating a skeleton and public health number
from the same table the existing POST endpoint should be removed in
favour of a new `PATCH: basic-details` endpoint.
TISNEW-5238
=> feat: Allow sync of public health number

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/QualificationResource.java, src/main/java/uk/nhs/hee/trainee/details/dto/QualificationDto.java, src/main/java/uk/nhs/hee/trainee/details/mapper/QualificationMapper.java, src/main/java/uk/nhs/hee/trainee/details/model/PersonalDetails.java, src/main/java/uk/nhs/hee/trainee/details/model/Qualification.java, src/main/java/uk/nhs/hee/trainee/details/model/TraineeProfile.java, src/main/java/uk/nhs/hee/trainee/details/service/QualificationService.java, src/main/java/uk/nhs/hee/trainee/details/service/impl/QualificationServiceImpl.java, src/main/java/uk/nhs/hee/trainee/details/service/impl/TraineeProfileServiceImpl.java, src/test/java/uk/nhs/hee/trainee/details/api/QualificationResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/impl/QualificationServiceImplTest.java
Qualifications should be stored in a sub-collection when synced. The
trainee profile will be populated with the latest qualification until a
later point, when the FE is expected to take the latest from the
qualifications collection.
TISNEW-5238
=> feat: Add endpoint to sync qualifications

.aws/task-definition.json, build.gradle, src/main/java/uk/nhs/hee/trainee/details/config/SentryConfiguration.java
Add the SENTRY_DSN and SENTRY_ENVIRONMENT environmental variables to the
task definition file. These values will be populated via the parameter
store in AWS.
NO-TICKET
=> chore: Add Sentry env vars to task definition

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java
The trainee's TIS id is being mistakenly set as the record id instead of
in to the traineeTisId field. This is causing duplicate key errors when
updating records as the profile can never be found by TIS ID.
NO-TICKET
=> fix: Trainee Id set in to record ID

.github/workflows/ci-cd-workflow.yml
The preprod service has been left without the `tis` prefix.
TIS21-1020: Create production pipelines
=> fix: use the git repository name as the prod service name

build.gradle, src/main/java/uk/nhs/hee/trainee/details/dto/PlacementDto.java, src/main/java/uk/nhs/hee/trainee/details/model/Placement.java
Add `employingBody`, `trainingBody` and `wholeTimeEquivalent` to the
placement DTO and model types.
TIS21-1032
=> feat: Add missing placement fields to DTO/model

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
The sort applied to qualifications does not handle the qualification
date being null, add a `nullLast` condition to place any qualifications
with nulls dates at the end of the list without throwing errors.
TIS21-1624
=> fix: Handle null qualification dates

.github/workflows/ci-cd-workflow.yml, Dockerfile
The bump to org.springframework.boot 2.5+ means that running 'gradlew
assemble' creates both the fatjar and the jar without dependencies
(*-plain.jar).
The problem is that the Dockerfile attempts to copy both files
to app.jar, so Dockerize fails with:
Step 3/4 : COPY build/libs/*.jar app.jar
When using COPY with more than one source file, the destination must be a directory and end with a /
Error: Process completed with exit code 1.
=> Chore: use bootBuildImage instead of dockerfile

build.gradle, src/main/java/uk/nhs/hee/trainee/details/config/MongoConfiguration.java, src/test/java/uk/nhs/hee/trainee/details/config/MongoConfigurationTest.java
Queries against the email field are incredibly slow, add an index on
that field so the profiles can be queries and returned quickly.
TIS21-1711
=> fix: Add index to the email field

build.gradle, src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDto.java, src/main/java/uk/nhs/hee/trainee/details/dto/deserializer/LowerCaseDeserializer.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/ContactDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDtoTest.java, src/test/java/uk/nhs/hee/trainee/details/dto/deserializer/LowerCaseDeserializerTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
During self sign up a match must be made against a TraineeProfile using
the sign up email address.
Due to limitation on DocumentDBs ability to query with case insensivity
any incoming emails should be set to lower cased before persisting or
querying with them.
TIS21-2436
=> fix: Force email to lower case

build.gradle, src/main/resources/application.yml
Change the logging level for `org.springframework.data` to `INFO` instead of `DEBUG`
NO-TICKET
=> fix: remove spring data debug logging

build.gradle, src/main/java/uk/nhs/hee/trainee/details/repository/TraineeProfileRepository.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
The trainee profile delete endpoint tried to delete by `_id` field, but
should use `traineeTisID`.
TIS21-2549
=> fix: use correct field name for trainee delete

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/QualificationResource.java, src/main/java/uk/nhs/hee/trainee/details/service/QualificationService.java, src/test/java/uk/nhs/hee/trainee/details/api/QualificationResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/QualificationServiceTest.java
If the qualification is not found by trainee and qualification IDs then
a 404 is returned, however this failure then hits the DLQ.
A `204 No Content` response is valid in the case of an object already
being deleted and should be used instead so that it can be categorised
as a success instead of failure.
TIS21-2549
=> fix: return 204 when qualification delete called

README.md, build.gradle, src/main/java/uk/nhs/hee/trainee/details/TisTraineeDetailsApplication.java
`springfox-swagger` is not currently compatible with the latest
Spring(Boot) versions. Given that none of our APIs are actually properly
annotated for Swagger the easiest fix for the runtime issue is to remove
the swagger dependencies.
NO-TICKET
=> chore: remove springfox-swagger dependencies

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/ContactDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/GdcDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/GmcDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PersonOwnerResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PersonalInfoResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/api/QualificationResource.java, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java
The logging when an API endpoint is triggered is currently `trace` but
the default logging output is `info`. As a result the service does not
currently log anything.
Raise the API entry logging level to `info`.
TIS21-SHED
=> fix: raise logging level for API endpoint entry

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
by filtering out invalid GMC profiles
Duplicate profile with the same email and their GMC numbers: [Link](https://healtheducationengland.sharepoint.com/:x:/s/TISys/EQWkau13QGdHkPYeZpu8exEBOdTyDAx3j7F_GahpssM7YA)
The logic is based on the following rules:
- TSS does not include dental ATM, so the validation of GDC is not considered
- if there is only one profile found by email, always return that single one even if it does not have valid GMC no.
- when multiple profiles are found, if there is no profile having a valid GMC no, return all profiles found by email
TIS21-3094: To identify common trends on duplicate records. Investigate the issue with the same email address being used on multiple records.
=> fix: duplicate Trainee profiles for the same email issue

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java
The person owner attribute is used to determine who a user should
contact for support, in the scenario where the person owner is removed
or otherwise nulled in TIS the user should be directed towards their
last LO for support. To allow this the last known person owner value
should be retained when it is removed in TIS.
TIS21-2858
=> fix: retain existing owner when TIS set to null

src/test/java/uk/nhs/hee/trainee/details/TestJwtUtil.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
Refactor TraineeProfileResourceTest to move the JWT token generation code to a new TestJwtUtil class.
Allows reuse of code for upcoming tests that will also need to generate tokens in this way.
TIS21-3685
=> test: Extract token generation to a utility class

src/main/java/uk/nhs/hee/trainee/details/api/PlacementCredential.java, src/test/java/uk/nhs/hee/trainee/details/api/PlacementCredentialTest.java
Add tests for the PlacementCredential API class, the successful response has been tweaked to return the full credential issue URI instead of just forwarding the gateway result to the frontend. This approach means the frontend does not need any knowledge about the gateway API or client ID.
=> test: placement credential resource

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/JwtService.java, src/test/java/uk/nhs/hee/trainee/details/service/JwtServiceTest.java
The application property names are in the format `dsp.slash-separated` but the JwtService expects a `dsp.dot.separated` format. This is working in some environments as Spring maps env vars directly, but we should be using the application properties value instead of direct env mapping.
TIS21-SHED
=> fix: incorrect DSP property mappings

.aws/task-definition-template.json, README.md, build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/ContactDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/GdcDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/GmcDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PersonOwnerResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PersonalInfoResource.java, src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/api/QualificationResource.java, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/config/AwsXrayConfiguration.java, src/main/java/uk/nhs/hee/trainee/details/config/AwsXrayInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/service/EventPublishService.java, src/main/java/uk/nhs/hee/trainee/details/service/JwtService.java, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/main/java/uk/nhs/hee/trainee/details/service/QualificationService.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/config/AwsXrayConfigurationTest.java
Configure the app to enable AWS XRay tracing for the rest controller and service beans.
The filter name includes the environment (preprod/prod) to allow differentiation in the traces.
TIS21-4224
TIS21-4227
=> feat: add tracing to API and Service classes

build.gradle, src/main/java/uk/nhs/hee/trainee/details/mapper/ProgrammeMembershipMapper.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
When patching a ProgrammeMembership the Conditions of Joining should not be overwritten unless the new value is not null. This avoids any "unsigning" of the CoJ when syncing data changes from TIS. This fix is required until CoJ data is available in TIS and synced via `tis-trainee-sync`.
TIS21-4460
TIS21-4375
=> feat: retain COJ status when patching PMs

.aws/task-definition-template.json, build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/config/RabbitConfig.java, src/main/java/uk/nhs/hee/trainee/details/service/RabbitPublishService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/config/RabbitConfigTest.java, src/test/java/uk/nhs/hee/trainee/details/service/EventPublishServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/RabbitPublishServiceTest.java
Note: this has been put together without a lot of RabbitMQ experience. The tests may be inadequate, and the implementation in general may offer scope for improvements.
Don't merge until TIS21-4456 done.
TIS21-4455: Event handler to push CoJ data to Rabbit exchange/queue
=> fix: use Rabbit for CoJ signing event queue

src/test/java/uk/nhs/hee/trainee/details/service/CachingDelegateIntegrationTest.java
The CachingDeletegate integration tests pass locally and in the PR workflow but fail in the CI/CD workflow for unknown reasons. There is an immediate need to get the functionality deployed, so the tests should be disabled temporarily.
TIS21-4460
=> test: disable integration test

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
When a PM has multiple curriculums the PM ID comes through as a concatenated list of CurriculumMembership IDs.
When deleting a PM and restoring the existing COJ from cache the concatenated IDs should be properly handled.
TIS21-4460
TIS21-4375
=> fix: handle coj cache for multi-curriculum PMs

build.gradle, src/main/java/uk/nhs/hee/trainee/details/config/ApplicationConfiguration.java, src/main/java/uk/nhs/hee/trainee/details/config/AwsXrayInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/config/EcsMetadataConfiguration.java, src/main/java/uk/nhs/hee/trainee/details/config/SentryConfiguration.java, src/test/java/uk/nhs/hee/trainee/details/config/ApplicationConfigurationTest.java, src/test/java/uk/nhs/hee/trainee/details/config/AwsXrayInterceptorTest.java, src/test/java/uk/nhs/hee/trainee/details/config/EcsMetadataConfigurationTest.java, src/test/java/uk/nhs/hee/trainee/details/config/SentryConfigurationTest.java
The ECS metadata endpoint provides information about what and where an instance of this service is running. Including that information on X-Ray traces and Sentry error captures allows easy identification of where an issue is occuring.
Update the X-Ray and Sentry configurations to include the ECS metadata. When not running in an ECS environment (i.e. the metadata endpoint is not provided) the X-Ray and Sentry reports should not include extra metadata e.g. showing null values.
TIS21-4439
TIS21-4379
=> feat: log ECS metadata with X-Ray and Sentry

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
The synchronization of ProgrammeMemberships has been refactored and no longer requires all PMs to be deleted from the TraineeProfile. Create a new API endpoint to allow the deletion of a single PM given the trainee and PM IDs.
TIS21-4172
TIS21-2399
=> feat: create endpoint for delete of single PM

build.gradle, src/main/java/uk/nhs/hee/trainee/details/dto/CurriculumDto.java, src/main/java/uk/nhs/hee/trainee/details/model/Curriculum.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/main/java/uk/nhs/hee/trainee/details/service/RabbitPublishService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/RabbitPublishServiceTest.java
Initial speculative branch to validate approach. 
Requires programme membership curricula to have tisId populated to work - a change that needs to be made in tis-trainee-sync.
TIS21-4659
=> Feat: pm id or UUID CoJ handling

build.gradle, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
Until migration to UUID style is complete.
TIS21-4699
=> fix: hide UUID programme memberships

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
If the legacy Programme Membership data is structured incorrectly, i.e. as two PMs instead of one with multiple curricula, it is possible for a valid COJ to not be copied over to the new UUID PM. This occurs when the first returned PM has a COJ but subsequent matching PMs do not, the later `null` values overwrite the originally assigned COJ.
Add a null check and a break to ensure that we only set COJ values that are non-null and exit the loop early if we've found a COJ already.
TIS21-2399
=> fix: skip processing after finding 1st legacy COJ

build.gradle, src/main/java/uk/nhs/hee/trainee/details/config/AmazonSqsConfig.java, src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDto.java, src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsUpdateEvent.java, src/main/java/uk/nhs/hee/trainee/details/event/BasicDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/ContactDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/GdcDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/GmcDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/PersonOwnerListener.java, src/main/java/uk/nhs/hee/trainee/details/event/PersonalInfoListener.java, src/test/java/uk/nhs/hee/trainee/details/config/AmazonSqsConfigTest.java, src/test/java/uk/nhs/hee/trainee/details/event/BasicDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/ContactDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/GdcDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/GmcDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/PersonOwnerListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/PersonalInfoListenerTest.java
The data structure for the PersonalDetailsEvent does not currently match the data that is sent from tis-trainee-sync.
Update the event DTO to more closely reflect the structure of the incoming message data.
Add SQS config to ensure that messages are read correctly.
Add an alias to the PersonalDetailsDto to ensure that `owner` can be correctly mapped to `personOwner`.
TIS21-4086
TIS21-4076
=> refactor: the personal details update event

build.gradle, src/main/java/uk/nhs/hee/trainee/details/dto/SiteDto.java, src/main/java/uk/nhs/hee/trainee/details/model/Placement.java, src/main/java/uk/nhs/hee/trainee/details/model/Site.java, src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
Create a Site entity and SiteDto to standardize the fields used to represent sites.
Update the existing Placement entity and PlacementDto to include a collectioin of Other Sites as well as use the Site entity/dto for the existing site fields. Those existing fields will be unwrapped automatically so that the existing DTO/DB structures are unchanged.
TIS21-4970
TIS21-4396
=> feat: add Other Sites to placement records

build.gradle, src/main/java/uk/nhs/hee/trainee/details/dto/ConditionsOfJoiningDto.java, src/main/java/uk/nhs/hee/trainee/details/model/ConditionsOfJoining.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/CachingDelegateIntegrationTest.java, src/test/java/uk/nhs/hee/trainee/details/service/CachingDelegateTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/RabbitPublishServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
=> feat: CoJ receivedFromTis

build.gradle, src/main/java/uk/nhs/hee/trainee/details/migration/DeleteDuplicateTraineeProfileProgrammeMemberships.java, src/test/java/uk/nhs/hee/trainee/details/migration/DeleteDuplicateTraineeProfileProgrammeMembershipsTest.java
Dependent on
https://github.com/Health-Education-England/tis-trainee-details/pull/380 merged, TIS CoJ DMS redrive and checks on all UUID-style PMs CoJs having receivedFromTis set.
TIS21-4715
=> feat: migrator delete old programme memberships

build.gradle, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
Depended on https://github.com/Health-Education-England/tis-trainee-details/pull/381
TIS21-5063
=> chore: tidying up programme membership service and tests

build.gradle, settings.gradle
Most of the changes required to migrate the build scripts to Kotlin DSL can be implemented up front and as supported in the Groovy DSL. Update the Gradle build script and settings to
- Use `"` instead of `'`
- Use parentheses for function calls
- Exclude parentheses for core plugins, as these will be treated differently
- Use `task` prefix to differentiate task config vs plugin config
- Use `.set()` for some config known to use Kotlin `val`
TIS21-SHED
=> build: prepare for kotlin DSL migration

build.gradle.kts, settings.gradle, settings.gradle.kts
Kotlin DSL is now the default for Gradle, migrate the Groovy based build script to Kotlin.
TIS21-5521
TIS21-5523
=> build: migrate Gradle to Kotlin DSL

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
One thing to consider is whether the sequencing is going to work correctly. For example, if a new programme membership arrives at tis-trainee-sync from TIS, this will trigger the update in tis-trainee-details, but also be broadcast to e.g. tis-trainee-notifications. If tis-trainee-notifications then calls the tis-trainee-details `isnewstarter` API before tis-trainee-details has processed the new programme membership, it would get a (potentially incorrect) negative response. 🤔 
Andy's proposed solution is to implement a slight delay on the SNS queues to ensure tis-trainee-profile updates the trainee profile before other events are triggered. I'll raise a PR for that separately.
TIS21-5723
=> feat: new starter API endpoint

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
Fix Health Education England South West Pilot logic with `noneMatch` to exclude Programme Membership with any one of the curriculum specialty is "General Practice"
(the current one would return true if one of the curriculum specialty is not "General Practice")
=> fix: South West Pilot Logic to exclude GP specialty in all curricula

.aws/task-definition-template.json
A bit of a stab in the dark in terms of fixing deployment, but we are seeing single tasks maxing out CPU so we should give it a little more either way.
=> chore: increase task cpu to 512

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/NtnGenerator.java, src/test/java/uk/nhs/hee/trainee/details/service/NtnGeneratorTest.java
The start and end date checks for curricula incorrect filter out
curricula that are starting or ending on the given day.
Update the NtnGenerator to check date equality as well as before/after.
TIS21-6175
TIS21-6182
---
The NTN should be calculated for future programme memberships, using the
start date as a filter.
i.e. the NTN will only consider curricula which start, or have somehow
started, on the day the programme starts for that trainee.
TIS21-6175
TIS21-6182
=> fix(ntn): curricula date filtering

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/NtnGenerator.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/NtnGeneratorTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
Generate and store the NTN when a programme membership is created or updated.
The NTN will still be regenerated when the profile is retrieved, until a scheduled job is put in place to allow starting/ending curricula to trigger an update to the stored NTN value.
TIS21-6175
TIS21-6182
=> feat: generate NTN when PMs are created/updated

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/NtnGenerator.java, src/test/java/uk/nhs/hee/trainee/details/service/NtnGeneratorTest.java
The managing deanery should be `Health Education England Yorkshire and the Humber` and not `Health Education England Yorkshire and The Humber`.
TIS21-6175
TIS21-6182
=> fix(ntn): capitalization of managing deanery

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/dto/ProgrammeMembershipDto.java, src/main/java/uk/nhs/hee/trainee/details/mapper/ProgrammeMembershipMapper.java, src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java, src/main/java/uk/nhs/hee/trainee/details/model/ProgrammeMembership.java, src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapperTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java
The NTN field is used for both NTN and DRN training numbers, rename the field and other related code to use Training Number instead.
TIS21-6175
TIS21-6182
=> refactor: rename NTN to training number

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java, src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java
The prefix used by South West has been changed to a single value of `SWN` instead of `PEN` or `SEV`.
Update the TrainingNumberGenerator to map directly and remove any special handling.
TIS21-6340
TIS21-6343
=> fix(ntn): South West NTN prefix

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/event/GmcDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/event/GmcDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java
Add an endpoint at `/api/basic-details/gmc-number` that allows a trainee to update their GMC number via a `PUT` request.
TIS21-6292
TIS21-6347
=> feat: add endpoint to update GMC number

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/RestResponseEntityExceptionHandler.java, src/main/java/uk/nhs/hee/trainee/details/dto/GmcDetailsDto.java, src/main/java/uk/nhs/hee/trainee/details/dto/validation/UserUpdate.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/RestResponseEntityExceptionHandlerTest.java
Create a custom RestResponseEntityExceptionHandler to handle the inclusion of validation failure messages in API responses. Follow the ProblemDetails structure with JSON Pointers used for request body based validation.
Example:
```json
{
"type": "about:blank",
"title": "Validation failure",
"status": 400,
"instance": "/trainee/api/basic-details/gmc-number",
"errors": [
{
"pointer": "#/gmcNumber",
"detail": "must be 7 digits"
}
]
}
```
Refactor the update GMC endpoint to accept a request body instead of a path variable containing the GMC number. Add validation to ensure that the GMC number is valid and the GMC status is not provided by the caller.
TIS21-6292
TIS21-6347
=> feat: return validation errors in REST response

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java
The Local Office names are being renamed to remove the "Health Education England" prefix, as there is no clean cut switch-over period both the new and old names will have to be handled for a short time. Once the new local office names are fully synced the old ones can be removed.
TIS21-6418
TIS21-6419
=> refactor: include new local office names

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TraineeProfileServiceTest.java
Currently PAST programmes are filtered out, but they now need to be shown.
At the same time an attempt to filter placements in the same way fails because the placement status is only ever `CURRENT` or `null`.
Update TraineeProfileResource to remove the filtering of past data. Update TraineeProfileService to remove the functions that perform the filtering, along with a filter for deprecated programmes which is no longer used.
TIS21-6386
TIS21-6387
TIS21-6388
=> fix: show all programmes

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java, src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java
The NTN generation will fail if the GMC number is `null` instead of falling back to an existing GDC number.
TIS21-6425
=> fix: handle null GMC number during NTN generation

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/main/java/uk/nhs/hee/trainee/details/service/TrainingNumberGenerator.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/TrainingNumberGeneratorTest.java
Local office names have been updated to remove the "Health Education England" prefix.
Previously the new names were put in alongside the legacy names, now the migration is complete the legacy names can be removed.
TIS21-6418
TIS21-6420
=> feat: remove legacy local office names

src/main/java/uk/nhs/hee/trainee/details/api/PlacementResource.java, src/main/java/uk/nhs/hee/trainee/details/service/PlacementService.java, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/api/PlacementResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/PlacementServiceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
Exclude non-onboarded trainees when assessing pilot placement inclusion, this category includes Dental, Foundation and Public Health trainees.
Placement exclusion can be based on the grade matching one of
- `DCT1`
- `DCT2`
- `DCT3`
- `DFT`
- `F1`
- `F2`
Programme Membership exclusion can be based on the specialty name matching one of
- "Public Health Medicine"
- "Foundation"
Or Programme Membership type matching one of
- `VISITOR`
- `LAT`
Or no curricula sub-type matching
- `MEDICAL_CURRICULUM`
- `MEDICAL_SPR`
TIS21-6643
=> feat: exclude non-onboarded trainees

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/DockerImageNames.java, src/integrationTest/java/uk/nhs/hee/trainee/details/TisTraineeDetailsApplicationIntegrationTest.java, src/integrationTest/resources/application-test.yml
Create an integration test module, it should run after unit tests as part of the `check` task.
Create an application integration test to verify that the spring context can load.
Existing "integration like" tests have not been refactored/moved in to the new module yet.
NO-TICKET
=> test: create integration test module

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipService.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
to make sure the LO contact is not displayed as blank when the contact is null
=> fix: add default Local Office contact message for null contact

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResource.java, src/main/java/uk/nhs/hee/trainee/details/api/TraineeProfileResource.java, src/main/java/uk/nhs/hee/trainee/details/config/InterceptorConfiguration.java, src/main/java/uk/nhs/hee/trainee/details/dto/TraineeIdentity.java, src/main/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptor.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/config/InterceptorConfigurationIntegrationTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorIntegrationTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorTest.java
Create a TraineeIdentityInterceptor to inject trainee identity details
(traineeTisId) in to the request scope.
The interceptor will run on each request and provides a single place
where the JWT token needs to be handled to extract the trainee ID. The
TraineeIdentity can be autowired in to any existing controllers and will
be auto-populated with the trainee ID.
---
Refactor the existing controllers which are currently handling
extracting the trainee ID from the auth token themselves. Autowire a
TraineeIdentity to the controllers and get the trainee ID from it.
=> refactor: inject trainee ID in to controllers

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/TestJwtUtil.java, src/integrationTest/java/uk/nhs/hee/trainee/details/TisTraineeDetailsApplicationIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/integrationTest/java/uk/nhs/hee/trainee/details/repository/CctCalculationRepositoryIntegrationTest.java, src/integrationTest/resources/application-test.yml, src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java, src/main/java/uk/nhs/hee/trainee/details/dto/CctCalculationDetailDto.java, src/main/java/uk/nhs/hee/trainee/details/dto/enumeration/CctChangeType.java, src/main/java/uk/nhs/hee/trainee/details/dto/validation/Create.java, src/main/java/uk/nhs/hee/trainee/details/exception/NotRecordOwnerException.java, src/main/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/mapper/CctMapper.java, src/main/java/uk/nhs/hee/trainee/details/model/CctCalculation.java, src/main/java/uk/nhs/hee/trainee/details/repository/CctCalculationRepository.java, src/main/java/uk/nhs/hee/trainee/details/service/CctService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorTest.java, src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java
Create GET and POST endpoints for CCT calculations, the GET path should
be `/api/cct/calculation/{calculationId}` and the POST should be
`/api/cct/calculation`.
The only currently supported CCT change type is LTFT.
Previously each endpoint that required a trainee ID checked for the ID
and returned `400 Bad Request` if the ID was missing. Now there is a
centralised place for managing the `custom:tisId` token property the
trainee ID check can be done in a single place.
However, several existing endpoints are private/internal and do not
receive a token at all.
Update the TraineeIdentityInterceptor to reject only requests to the CCT
controller if the trainee ID is missing. In such cases a `403 Forbidden`
should be returned.
The interceptor can take over verification for other endpoints once …
=> feat: GET and POST CCT calculations endpoints

build.gradle.kts, src/main/resources/application.yml
UUIDs stored in the database are using the old UUID format (binData sub-type 3) instead of the new UUID format (binData sub-type 4).
Update the application configuration to use the new UUID format when storing UUIDs.
TIS21-6544
TIS21-6623
=> fix: database UUID format

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/dto/CctCalculationDetailDto.java
Note: validation is not applied in the unit tests, so the only 'test' for this is by implication in the integration tests.
TIS21-6761
=> fix: create validation relaxed

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java, src/main/java/uk/nhs/hee/trainee/details/mapper/CctMapper.java, src/main/java/uk/nhs/hee/trainee/details/service/CctService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java
As per https://github.com/Health-Education-England/tis-trainee-api/blob/3c04e148fa14f831163c2e9d0d69c639ec5f7540/openapi/paths/trainee_cct_calculation.yml#L12
TIS21-6883
=> fix: CCT get endpoint to provide details not summaries

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/service/CctService.java, src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java
Omitted from https://github.com/Health-Education-England/tis-trainee-details/pull/508 . 
(The other issues were data-related with some legacy entries in the db with programme membership id in binary form, which have now been removed).
TIS21-6883
=> fix: include cctDate in cct list api response

build.gradle.kts, settings.gradle.kts
Use the [trainee version catalog](https://github.com/Health-Education-England/tis-trainee-version-catalog) to determine plugin and dependency versions.
The version catalog was based on `tis-trainee-details` so there are currently no version changes to any dependendencies.
NO-TICKET
=> build: migrate to version catalog

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/dto/ProgrammeMembershipDto.java, src/main/java/uk/nhs/hee/trainee/details/model/ProgrammeMembership.java, src/test/java/uk/nhs/hee/trainee/details/api/ProgrammeMembershipResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/ProgrammeMembershipServiceTest.java
The admin endpoints for LTFT forms require filtering based on the admin's local office, which can be determined using the `cognito:groups` from the auth token.
The group name is the DBC, rather than a name, so to avoid having to hardcode a mapping the code should be added to the PM so it can be referenced in the LTFT data.
TIS21-6599
TIS21-6938
=> feat: include DBC in programme membership

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/dto/PersonalDetailsDto.java, src/main/java/uk/nhs/hee/trainee/details/dto/UserDetails.java, src/main/java/uk/nhs/hee/trainee/details/mapper/TraineeProfileMapper.java, src/main/java/uk/nhs/hee/trainee/details/model/PersonalDetails.java, src/main/java/uk/nhs/hee/trainee/details/service/TraineeProfileService.java, src/test/java/uk/nhs/hee/trainee/details/api/TraineeProfileResourceTest.java
And include it in UserDetails and Profile DTOs for downstream handling.
Example traineeProfile:
```
{
"_id": {
"$oid": "5e00c7942749a84794644f83"
},
"traineeTisId": "47165",
"personalDetails": {
"surname": "Gilliam",
"forenames": "Anthony Mara",
"knownAs": "Ivy",
"maidenName": "N/A",
"title": "Mr",
"personOwner": "Thames Valley",
"role": [
"DR in Training",
"Dummy Record",
"Foundation Clinical Supervisor",
"x"
],
"dateOfBirth": {
"$date": "1991-11-11T00:00:00.000Z"
},
"gender": "Male",
"qualification": "MBBS Bachelor of Medicine and Bachelor of Surgery",
"dateAttained": {
"$date": "2018-05-29T23:00:00.000Z"
},
"medicalSchool": "University of Science and Technology",
"telephoneNumber": "01632960363",
"mobileNumber": "08465879348",
"email": "email@email.com",
"address1": "585-6360 Interdum …
```
=> feat: store personal details role

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/FeatureResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/api/FeatureResource.java, src/main/java/uk/nhs/hee/trainee/details/config/FeaturesProperties.java, src/main/java/uk/nhs/hee/trainee/details/dto/FeaturesDto.java, src/main/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/service/FeatureService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/api/FeatureResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/api/RestResponseEntityExceptionHandlerTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorTest.java, src/test/java/uk/nhs/hee/trainee/details/service/FeatureServiceTest.java
Create a feature flag for LTFT at `GET: /api/features` to return whether the trainee has a valid programme for LTFT.
Current rules are that the programme must not have ended and must be a a London or South West programme.
TIS21-6703
TIS21-6908
=> feat: feature flags for LTFT

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/FeatureResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/api/util/AuthTokenUtil.java, src/main/java/uk/nhs/hee/trainee/details/config/FeaturesProperties.java, src/main/java/uk/nhs/hee/trainee/details/dto/TraineeIdentity.java, src/main/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/service/FeatureService.java, src/main/resources/application.yml, src/test/java/uk/nhs/hee/trainee/details/api/util/AuthTokenUtilTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorTest.java, src/test/java/uk/nhs/hee/trainee/details/service/FeatureServiceTest.java
Members of the `beta-participant` group should always have the LTFT feature enabled, regardless of having a qualifying programme membership. Update the trainee identity to include the Cognito groups, use the groups to determine beta group membership when checking valid feature flags.
Refactor the FeaturesProperties to allow multiple tranches to be configured with individual start dates and deanery lists. The feature service should combine all started tranches when determining whether there is a valid PM or not.
Update the TraineeIdentityInterceptor to relax the trainee ID requirement on the feature flag endpoint.
Features will still be disabled via the FeatureService if there is no trainee ID, but the hard requirement in the interceptor causes authentication failures with ambiguous error …
=> feat(ltft): always enable for beta participants

build.gradle.kts, src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/dto/CctCalculationDetailDto.java, src/main/java/uk/nhs/hee/trainee/details/model/CctCalculation.java, src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java
The LTFT notifications require the managing deanery/local office name in order to determine the contacts/links to include in the notification. Update the CCT entity and DTO to include the managing deanery so that it is available to pass to the LTFT.
TIS21-6596
TIS21-6594
=> feat(cct): add managing deanery

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/event/ContactDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/GdcDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/GmcDetailsListener.java, src/main/java/uk/nhs/hee/trainee/details/event/PersonOwnerListener.java, src/main/java/uk/nhs/hee/trainee/details/event/PersonalInfoListener.java, src/main/java/uk/nhs/hee/trainee/details/model/PersonalDetailsUpdated.java, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/event/ContactDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/GdcDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/GmcDetailsListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/PersonOwnerListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/event/PersonalInfoListenerTest.java, src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java
On stage, when GMC details update return empty entity (due to TisId not found or no-change update), It shows "GMC number updated" with a blank profile page enough the trainee profile is not really updated.
Raising this PR to make sure the endpoint return bad request if details not updated.
=> fix: return bad request when GMC details update entity is empty

build.gradle.kts, src/main/java/uk/nhs/hee/trainee/details/api/BasicDetailsResource.java, src/main/java/uk/nhs/hee/trainee/details/service/PersonalDetailsService.java, src/test/java/uk/nhs/hee/trainee/details/api/BasicDetailsResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/service/PersonalDetailsServiceTest.java
The tester check is blocking the E2E tester (tisId -1) to update GMC number in the E2E test.
This is to allow test user (tisId start with "-") to update GMC number on TSS side, but just not to publish to TIS to avoid exception.
=> fix: allow test user update GMC in TSS but not publish to TIS

src/integrationTest/java/uk/nhs/hee/trainee/details/api/CctResourceIntegrationTest.java, src/main/java/uk/nhs/hee/trainee/details/api/CctResource.java, src/main/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptor.java, src/main/java/uk/nhs/hee/trainee/details/model/CctCalculation.java, src/main/java/uk/nhs/hee/trainee/details/service/CctService.java, src/test/java/uk/nhs/hee/trainee/details/api/CctResourceTest.java, src/test/java/uk/nhs/hee/trainee/details/interceptor/TraineeIdentityInterceptorTest.java, src/test/java/uk/nhs/hee/trainee/details/service/CctServiceTest.java
Note: ignores programme membership, which will be a broken link on the new trainee. Possibly we should limit the move to CCT calcs where the programme membership has ended?
Regardless, it doesn't break the FE; if you edit the new CCT calc the old PM name is simply not listed in the dropdown, as you would expect.
Downstream service effects: None.
TIS21-7634
=> feat: move CCT calcs to different trainee
